#define SIGNAL_FM_BASE                          0x1000
#define SIGNAL_FM_REQ_GET_FACES         SIGNAL_FM_BASE + 0x0001
#define SIGNAL_FM_RESP_GET_FACES        SIGNAL_FM_BASE + 0x0002
#define SIGNAL_FM_REQ_FACE_ADD          SIGNAL_FM_BASE + 0x0003
#define SIGNAL_FM_RESP_FACE_ADD         SIGNAL_FM_BASE + 0x0004
#define SIGNAL_FM_REQ_FACE_DELETE       SIGNAL_FM_BASE + 0x0005
#define SIGNAL_FM_RESP_FACE_DELETE      SIGNAL_FM_BASE + 0x0006
#define SIGNAL_FM_REQ_LOGIN             SIGNAL_FM_BASE + 0x0007
#define SIGNAL_FM_RESP_LOGIN_OK         SIGNAL_FM_BASE + 0x0008
#define SIGNAL_FM_RESP_LOGIN_FAILED     SIGNAL_FM_BASE + 0x0009
#define SIGNAL_FM_RESP_VIDEO_FRAME      SIGNAL_FM_BASE + 0x0010
